### ISSUE TITLE
Provide ability to disable all logging from  module

### ISSUE THREAD

**Issue by pceBuildMaster** [MarketSquare/robotframework-requests#215]
Wanted to inquire about providing a pull request that would allow user to control what is logged by this module.

Most logging from module is small, but a couple calls can be pretty large in Robotframework log depending on the response data.  For example I make API calls to my SUT that can return many KBytes of json data and this currently gets logged at the Debug level.  e.g. in _body_requests():

`self.builtin.log(method_name + ' response: ' + resp.text, 'DEBUG')`

Similar in to_json() at Info level:
```
logger.info('To JSON using : content=%s ' % (content))
logger.info('To JSON using : pretty_print=%s ' % (pretty_print))
```
The other logger.info are small but still can clutter up Info level in log when user is already logging what they want at each level.

**Comment by lucagiove** [comment]
Hi, I changed actually a bit the logging of this library, actually now logs more :) at least in debug mode.
It will log the whole response / request that's actually very useful for debug, I'd like to provide a max length parameters to eventually truncate the size in order to avoid too big logs.
Would that be enough for your needs or you need something different?
Let's discuss about logging.

Thanks!
Luca

**Comment by lucagiove** [comment]
Actually in 0.7 most probably with log level **info** the request and response body will be truncated by default after 10.000 chars.
Full body will be shown in debug / trace mode.
