### ISSUE TITLE
data formatting for requests on session keywords

### ISSUE THREAD

**Issue by AdomasSimonenkovas** [MarketSquare/robotframework-requests#312]
i upgraded robotframework-requests package to 0.8.0 version which caused a deprecation warning for * Request keywords. I tried updating my keywords to use * On Session, but my requests fail due to invalid encoding.  Is there a reason why the data formation according to header was removed from the newer keywords? I managed to get my testcases work by adding this line before the request is made
data = utils.format_data_according_to_header(session, data, session.headers)

Is there a reason why data formatting was removed from the new keywords?

**Comment by lucagiove** [comment]
Yes, the reason is that original Python requests library already does encoding in cases where is strictly needed and safe I didn't want to change the original library behavior.
Moreover in some situation you couldn't test not encoded payload.

Make sure that headers are written properly and if data is a json just use the json= parameter
