### ISSUE TITLE
How to test kong API with HMAC Authentication

### ISSUE THREAD

**Issue by sunkusowmyasree** [MarketSquare/robotframework-requests#337]
I am trying to test API's with a robot framework
In Postman We use to write a pre-request script to generate SigningStr with HMAC Authentication format. How to replicate this in robot frameowrk?

**Comment by lucagiove** [comment]
Hi, this is not a really RequestsLibrary related question but more RobotFramework I suggest you to ask on Slack or RF Forum because in your test you can prepare almost everything you want as script or with already existing RF keywords or libraries.
This library only takes care of HTTP communication.
I don't know the details of HMAC but I see there is a python library you might use: https://docs.python.org/3/library/hmac.html
