### ISSUE TITLE
Leaking of credentials when using HTTP Basic auth

### ISSUE THREAD

**Issue by nestoracunablanco** [MarketSquare/robotframework-requests#380]
When logging the request, in case we have are using basic authentication, credentials are leaked.
This is because the credentials are part of the header and it is also logged.

**Comment by lucagiove** [comment]
Mainly the idea could be to have a parsing function that search in headers keys for well known authentication mechanism and remove the sensitive data from log.
So I expect to find in log example Authorization: 'value-has-been-redacted'
Probably by default the redaction is enabled and can be disabled maybe at debug logging level.
This solution should consider performance since logging is quite cpu intensive when lot of requests are issued.

**Comment by nestoracunablanco** [comment]
Hello @lucagiove , I wanted to confirm if I understood you correctly. I have just submitted a PR, which is currently incomplete. The PR focuses on retrieving header information, verifying the presence of an authorization key, and masking it with asterisks. This practice is commonly used to prevent logging of sensitive information.

In addition, I can also incorporate functionality to enable based on the log level. However, before expanding the code further in the PR, I would appreciate your feedback on whether I am proceeding in the right direction.

**Comment by lucagiove** [comment]
[] add documentation for this new behavior

**Comment by nestoracunablanco** [comment]
Hello @lucagiove, thank you for merging the PR. I agree with the idea of documenting it. Would it be appropriate to include the documentation in the README.md, or do you have another specific location in mind?

**Comment by lucagiove** [comment]
Not in readme but in standard documentation: https://marketsquare.github.io/robotframework-requests/doc/RequestsLibrary.html

Maybe a new section: "logging or logs" could be created.
